//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGenerator.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersOnConfDays
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdersOnConfDays()
        {
            this.ParticipAtConfDay = new HashSet<ParticipAtConfDay>();
            this.WorkshopsSubOrders = new HashSet<WorkshopsSubOrders>();
        }
    
        public int OrdOnConfDayID { get; set; }
        public int DayOfConfID { get; set; }
        public int OrderID { get; set; }
        public short NumberOfRegularSeats { get; set; }
        public short NumberOfStudentSeats { get; set; }
    
        public virtual DaysOfConf DaysOfConf { get; set; }
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipAtConfDay> ParticipAtConfDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkshopsSubOrders> WorkshopsSubOrders { get; set; }
    }
}
