//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGenerator.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipAtConfDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipAtConfDay()
        {
            this.WorkshopsSubOrders = new HashSet<WorkshopsSubOrders>();
        }
    
        public int EntryID { get; set; }
        public int ParticipantID { get; set; }
        public int OrdOnConfDayID { get; set; }
    
        public virtual OrdersOnConfDays OrdersOnConfDays { get; set; }
        public virtual Participants Participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkshopsSubOrders> WorkshopsSubOrders { get; set; }
    }
}
