//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGenerator.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Value { get; set; }
        public string AccountNumber { get; set; }
        public string TitleOfPayment { get; set; }
        public string TransferSender { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
