//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGenerator.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceThresholds
    {
        public int ThresholdID { get; set; }
        public int DayOfConfID { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Value { get; set; }
    
        public virtual DaysOfConf DaysOfConf { get; set; }
    }
}
