//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGenerator.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshops
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workshops()
        {
            this.WorkshopsSubOrders = new HashSet<WorkshopsSubOrders>();
        }
    
        public int WorkshopID { get; set; }
        public int DayOfConfID { get; set; }
        public string Name { get; set; }
        public string TeacherName { get; set; }
        public string TeacherSurname { get; set; }
        public decimal Value { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public short SpaceLimit { get; set; }
    
        public virtual DaysOfConf DaysOfConf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkshopsSubOrders> WorkshopsSubOrders { get; set; }
    }
}
