//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGenerator.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkshopsSubOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkshopsSubOrders()
        {
            this.ParticipAtConfDay = new HashSet<ParticipAtConfDay>();
        }
    
        public int WorkshopSubOrderID { get; set; }
        public int WorkshopID { get; set; }
        public int OrdOnConfDayID { get; set; }
        public short NumberOfSeats { get; set; }
    
        public virtual OrdersOnConfDays OrdersOnConfDays { get; set; }
        public virtual Workshops Workshops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipAtConfDay> ParticipAtConfDay { get; set; }
    }
}
